Updating secret.js
ritsu-me/otoiro pull request #1
Opened 2023-05-08 10:15 UTC by ritsu-me

[add] .jsonにnpmパッケージ関係の記載を追記

2023-05-08 10:41 UTC, AsPulse requested changes

2023-05-08 10:41 UTC, AsPulse commented on secret.ts
> +} catch {/*nothing*/}
dotenv.configって何かthrowするんでしたっけ……。
使われてるdotenvが古めのバージョンで、調査が難しかった

最新版にアプデしてもいいかも!! (どうせならtop-level await使えるしProimiseにしちゃうのがosusume)

とりあえずcatchして何もしないのはえろいひとに怒られちゃうぞ!!!!

2023-05-08 10:51 UTC, ritsu-me reviewed
直します！

2023-05-08 14:26 UTC, ritsu-me reviewed
現時点これで動くのか不明ですが、開発用のブランチにつき現在稼働中のものとは別物になるので良しとします

2023-05-08 22:11 UTC, AsPulse requested changes

2023-05-08 22:11 UTC, AsPulse commented on secret.ts
> +import { Deno } from "discordeno/types/_dnt.shims.js"
なんかへんなのimportしとる…いらないはず！

2023-05-09 03:15 UTC, ritsu-me reviewed
行けるはずだけど動かないかも
DenoDeploy側はいじってみる

2023-05-09 06:25 UTC, AsPulse approved these changes
デプロイ通ってるね、LGTM!
（大丈夫だとは思うんだけど、previewに本番と同じTOKEN渡してないよね…？）

2023-05-09 06:25 UTC, AsPulse approved these changes
デプロイ通ってるね、LGTM!
（大丈夫だとは思うんだけど、previewに本番と同じTOKEN渡してないよね…？）

2023-05-09 06:45 UTC, ritsu-me commented
大丈夫です！

2023-05-09 06:45 UTC, merged